version: '3.0'

services:
  frontend:
    image: guiupssitech/upssijobs
    container_name: nuxt-app
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: upssinterships.tk 
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: upssinterships.tk
      LETSENCRYPT_EMAIL: guillaume.roussin44@gmail.com

  backend:
    image: augustodelg/pocketbase
    container_name: pocketbase
    volumes:
      - /srv/www/upssinterships.tk/pocketbase-data:/pb_data
    expose:
      - 8090
    environment:
      VIRTUAL_HOST: api.upssinterships.tk
      VIRTUAL_PORT: 8090
      LETSENCRYPT_HOST: api.upssinterships.tk
      LETSENCRYPT_EMAIL: guillaume.roussin44@gmail.com
    
networks:
  default:
    external:
      name: nginx-proxy